//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace request
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int id_Request { get; set; }
        public System.DateTime date_added { get; set; }
        public Nullable<int> equipmentId { get; set; }
        public int IssueTypeId { get; set; }
        public string Opisanie { get; set; }
        public Nullable<int> ispolnitelId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
    
        public virtual Equipmnt Equipmnt { get; set; }
        public virtual Ispolnitel Ispolnitel { get; set; }
        public virtual IssueType IssueType { get; set; }
        public virtual Status Status { get; set; }
    }
}
